### ISSUE TITLE
System Events TCC Pop Up

### ISSUE THREAD

**Issue by Ne0nd0g** [cedowens/SwiftBelt#2]
I wanted to share this as more of a heads up. The first time I ran the `-LaunchAgents` option I received this pop up:

![image](https://user-images.githubusercontent.com/5638474/83882476-2c229280-a710-11ea-9669-1f7f6db53376.png)

Full command was: `./SwiftBelt -ListUsers -LaunchAgents` on macOS 10.15.4

**Comment by cedowens** [comment]
Thank you! Yes, I removed that code locally (due to the pop up) but must have uploaded a prior version of the swift source code and binary...so I will update those shortly.

**Comment by cedowens** [comment]
Just updated the swift source code and the compiled binary to remove the "Login Item" enumeration from the "-LaunchAgents" option. Thanks again for reporting.
